# Generated by Django 6.0.6 on 2026-06-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('total_area_hectares', models.FloatField(default=0.0)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'farms',
            },
        ),
        migrations.CreateModel(
            name='FeedingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_kg', models.FloatField()),
                ('feeding_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'feeding_history',
                'ordering': ['-feeding_date'],
            },
        ),
        migrations.CreateModel(
            name='FishStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, help_text='Number of fish')),
                ('average_weight_grams', models.FloatField(default=0.0)),
                ('growth_stage', models.CharField(choices=[('fry', 'Fry (0-30 days)'), ('fingerling', 'Fingerling (1-3 months)'), ('juvenile', 'Juvenile (3-6 months)'), ('sub_adult', 'Sub-Adult (6-12 months)'), ('adult', 'Adult (12+ months)')], default='fingerling', max_length=20)),
                ('water_temperature', models.FloatField(blank=True, help_text='Celsius', null=True)),
                ('water_ph', models.FloatField(blank=True, null=True)),
                ('dissolved_oxygen', models.FloatField(blank=True, help_text='mg/L', null=True)),
                ('water_condition', models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=10)),
                ('water_type', models.CharField(choices=[('freshwater', 'Freshwater'), ('saltwater', 'Saltwater'), ('brackish', 'Brackish')], default='freshwater', max_length=20)),
                ('stocking_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fish_stocks',
            },
        ),
    ]
