# Generated by Django 6.0.6 on 2026-06-14 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        ('feeds', '0001_initial'),
        ('species', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='farmer',
            field=models.ForeignKey(limit_choices_to={'role': 'farmer'}, on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedinghistory',
            name='feed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeding_records', to='feeds.feedproduct'),
        ),
        migrations.AddField(
            model_name='fishstock',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fish_stocks', to='farms.farm'),
        ),
        migrations.AddField(
            model_name='fishstock',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fish_stocks', to='species.fishspecies'),
        ),
        migrations.AddField(
            model_name='feedinghistory',
            name='fish_stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_history', to='farms.fishstock'),
        ),
    ]
