# Generated by Django 6.0.6 on 2026-06-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('species', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedInventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('add', 'Stock Added'), ('sell', 'Stock Sold'), ('adjust', 'Manual Adjustment')], max_length=10)),
                ('quantity_kg', models.FloatField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'feed_inventory_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, max_length=200)),
                ('feed_form', models.CharField(choices=[('pellet', 'Pellet'), ('crumble', 'Crumble'), ('powder', 'Powder'), ('flake', 'Flake'), ('extruded', 'Extruded')], default='pellet', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='feeds/')),
                ('description', models.TextField(blank=True)),
                ('protein_percentage', models.FloatField()),
                ('fat_percentage', models.FloatField()),
                ('fiber_percentage', models.FloatField(default=0.0)),
                ('moisture_percentage', models.FloatField(default=0.0)),
                ('ash_percentage', models.FloatField(default=0.0)),
                ('energy_kcal_per_kg', models.FloatField(default=0.0)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('is_available', models.BooleanField(default=True)),
                ('stock_quantity_kg', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('suitable_species', models.ManyToManyField(blank=True, related_name='compatible_feeds', to='species.fishspecies')),
            ],
            options={
                'verbose_name': 'Feed Product',
                'verbose_name_plural': 'Feed Products',
                'db_table': 'feed_products',
            },
        ),
    ]
