# Generated by Django 6.0.6 on 2026-06-14 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feeds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feedproduct',
            name='supplier',
            field=models.ForeignKey(limit_choices_to={'role': 'supplier'}, on_delete=django.db.models.deletion.CASCADE, related_name='feed_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedinventorylog',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_logs', to='feeds.feedproduct'),
        ),
    ]
