# Generated by Django 6.0.6 on 2026-06-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_parameters', models.JSONField()),
                ('predicted_feed_group', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'recommendations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(default=1)),
                ('match_percentage', models.FloatField()),
                ('nutritional_score', models.FloatField()),
                ('group_score', models.FloatField()),
                ('explanation', models.TextField(blank=True)),
                ('composition_snapshot', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'recommendation_results',
                'ordering': ['rank'],
            },
        ),
    ]
