# Generated by Django 6.0.6 on 2026-06-14 13:19

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FishSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('scientific_name', models.CharField(blank=True, max_length=200)),
                ('habitat', models.CharField(max_length=200)),
                ('water_type', models.CharField(choices=[('freshwater', 'Freshwater'), ('saltwater', 'Saltwater'), ('brackish', 'Brackish')], max_length=20)),
                ('growth_stage', models.CharField(choices=[('fry', 'Fry (0-30 days)'), ('fingerling', 'Fingerling (1-3 months)'), ('juvenile', 'Juvenile (3-6 months)'), ('sub_adult', 'Sub-Adult (6-12 months)'), ('adult', 'Adult (12+ months)')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='species/')),
                ('description', models.TextField(blank=True)),
                ('min_protein_requirement', models.FloatField(help_text='Minimum protein % required in feed')),
                ('max_protein_requirement', models.FloatField(help_text='Maximum protein % in feed')),
                ('min_fat_requirement', models.FloatField(help_text='Minimum fat % required in feed')),
                ('max_fat_requirement', models.FloatField(help_text='Maximum fat % in feed')),
                ('min_fiber_requirement', models.FloatField(default=0.0)),
                ('max_fiber_requirement', models.FloatField(default=10.0)),
                ('min_moisture_requirement', models.FloatField(default=0.0)),
                ('max_moisture_requirement', models.FloatField(default=15.0)),
                ('optimal_temp_min', models.FloatField(default=20.0, help_text='Celsius')),
                ('optimal_temp_max', models.FloatField(default=30.0, help_text='Celsius')),
                ('optimal_ph_min', models.FloatField(default=6.5)),
                ('optimal_ph_max', models.FloatField(default=8.5)),
                ('optimal_do_min', models.FloatField(default=5.0, help_text='mg/L dissolved oxygen')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Fish Species',
                'verbose_name_plural': 'Fish Species',
                'db_table': 'fish_species',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='fish_specie_search__c407b9_gin')],
            },
        ),
    ]
